NAME=tarpn-mon
SUMMARY=Monitoring backend and web interface (replaces TARPN Home)
VERSION=1
REQUIRES=core
UNITS=tarpn-mon.service
ENABLE=tarpn-mon.service
REQUIRED=false
BINARY=tarpn-mon
PROVIDES=monitor
